
import React from "react";

const Disclaimer = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold mb-8">Disclaimer for GigsTyping</h1>
      
      <p className="mb-6">
        Welcome to GigsTyping! Before using our typing speed test tool, please carefully read and understand 
        the following disclaimer. By accessing or using our platform, you acknowledge that you have read, 
        understood, and agreed to the terms outlined below.
      </p>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">No Guarantee of Accuracy</h2>
        <p className="text-gray-700">
          While we strive to provide accurate and reliable results, GigsTyping makes no guarantees regarding 
          the precision or correctness of the typing speed calculations, accuracy scores, or any other data 
          generated by the tool. The results provided are intended for informational and educational purposes 
          only and should not be considered definitive or professional assessments.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Use at Your Own Risk</h2>
        <p className="text-gray-700">
          Your use of GigsTyping is entirely at your own risk. The platform is provided on an "as-is" and 
          "as-available" basis without warranties of any kind, either express or implied. This includes, 
          but is not limited to, warranties of merchantability, fitness for a particular purpose, or 
          non-infringement. We do not guarantee that the platform will be error-free, uninterrupted, or 
          free from viruses or other harmful components.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Limitation of Liability</h2>
        <p className="mb-3">
          GigsTyping shall not be held liable for any damages, losses, or injuries arising out of or related 
          to your use of the platform. This includes, but is not limited to:
        </p>
        <ul className="list-disc ml-6 text-gray-700 space-y-2">
          <li>Direct, indirect, incidental, consequential, or punitive damages.</li>
          <li>Loss of data, revenue, profits, or business opportunities.</li>
          <li>Any errors, omissions, or inaccuracies in the content or functionality of the platform.</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Third-Party Content and Advertisements</h2>
        <p className="text-gray-700">
          GigsTyping may display advertisements or links to third-party websites, products, or services. 
          These third-party entities are independent of GigsTyping, and we do not endorse, verify, or assume 
          responsibility for their content, practices, or offerings. Your interactions with third parties, 
          including through advertisements or linked websites, are solely between you and the respective third party.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">User Responsibility</h2>
        <p className="text-gray-700">
          You are solely responsible for ensuring that your use of GigsTyping complies with all applicable 
          laws, regulations, and guidelines. You agree not to misuse the platform or engage in activities 
          that could harm its functionality, security, or reputation.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Educational Purpose Only</h2>
        <p className="text-gray-700">
          GigsTyping is designed as an educational tool to help users practice and improve their typing skills. 
          It is not intended to replace professional training, certification, or employment-related assessments. 
          Any reliance on the results or features of the platform for such purposes is done at your own discretion.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold mb-4">Changes to the Disclaimer</h2>
        <p className="text-gray-700">
          We reserve the right to update or modify this disclaimer at any time without prior notice. 
          Any changes will take effect immediately upon posting on the website. It is your responsibility 
          to review this page periodically to stay informed about the latest terms.
        </p>
      </section>
    </div>
  );
};

export default Disclaimer;
